spring:
  profiles:
    active: local

spring.batch.job.names: ${job.name:NONE}
---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
        driver-class-name: org.h2.Driver
#---
#spring:
#  profiles: oracle
#  datasource:
#    hikari:
#      jdbc-url: jdbc:oracle:thin:@localhost:1521/xepdb1
#      username: philz
#      password: 1234
#      driver-class-name: oracle.jdbc.driver.OracleDriver
---
spring:
  profiles: oracle
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xepdb1
    username: philz
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver